// Generated by Wrangler on Fri Apr 19 2024 16:15:32 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  ENVIRONMENT: string;
  IMAGE_SOURCE_URL: string;
  IMAGE_TRANSFORM_URL?: string;
  MAIL_API_URL: string;
  MAIL_TO: string;
  MAIL_API_KEY: string;
  AUTH_SECRET: string;
  AUTH_GOOGLE_ID: string;
  AUTH_GOOGLE_SECRET: string;
  AUTH_GITHUB_ID: string;
  AUTH_GITHUB_SECRET: string;
  DB: D1Database;
}
