#:schema node_modules/wrangler/config-schema.json
name = "spacedog-nextjs"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "spacedog"
database_id = "5dbd9d69-e0a3-45d8-880f-71b23eca8e5f"

[vars]
NEXT_PUBLIC_IMAGE_SOURCE_URL = "https://image.spacedog.com.au:444"
NEXT_PUBLIC_IMAGE_TRANSFORM_URL = "https://spacedog.com.au"
MAIL_API_URL = "https://api.sendgrid.com/v3/mail/send"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "spacedog"
database_id = "5dbd9d69-e0a3-45d8-880f-71b23eca8e5f"

[env.preview.vars]
NEXT_PUBLIC_IMAGE_SOURCE_URL = "https://image.spacedog.com.au:444"
NEXT_PUBLIC_IMAGE_TRANSFORM_URL = "https://spacedog.com.au"
MAIL_API_URL = "https://api.sendgrid.com/v3/mail/send"

[[env.production.d1_databases]]
binding = "DB"
database_name = "spacedog"
database_id = "5dbd9d69-e0a3-45d8-880f-71b23eca8e5f"

[env.production.vars]
NEXT_PUBLIC_IMAGE_SOURCE_URL = "https://image.spacedog.com.au:444"
MAIL_API_URL = "https://api.sendgrid.com/v3/mail/send"
